Bot commentator
soboleva8/Comment_Bot_Grammy pull request #2
Opened 2024-03-12 21:26 UTC by soboleva8

This code is for a bot that creates the very first comment on a post in the selected Telegram channel.

2024-03-14 10:35 UTC, Kreozot requested changes

2024-03-14 10:35 UTC, Kreozot commented on app.js
> +const textMessage = data.comment_rules;
Зачем тут JSON? Мы же можем сразу получать строку
```suggestion
const { COMMENT_TEXT } = process.env;
```

2024-03-14 10:35 UTC, Kreozot commented on app.js
> +    console.dir(ctx.message, { depth: null });
Все `console` логи обычно удаляются из проекта. Для логирования лучше использовать другие средства, но это потом.

2024-03-14 10:35 UTC, Kreozot commented on app.js
>  const CHANNEL_ID = +process.env.CHANNEL_ID;
`+` это неочевидный способ перевода в тип number. Лучше использовать `Number(MY_VAR)` прямо там, где мы используем эту переменную.

Но вообще я смотри что нашёл: https://www.npmjs.com/package/envalid

Предлагаю тебе посмотреть эту либу и попробовать использовать её для получения переменных из process.env. Ты там должен будешь вызвать функцию, передав правила форматирования для своих переменных, и она уже сделает всё что нужно. Затем ты уже импортируешь переменные из provess.env и они будут с теми типами, которые тебе нужны.

2024-03-14 10:35 UTC, Kreozot commented on app.js
> +        const commentChatId = ctx.chat.id;
В целом нам не нужно объявлять новую константу если это не приводит к уменьшению или упрощению кода (например когда `ctx.chat.id` у тебя используется в пяти разных местах) или повышению читабельности (например когда у тебя какая-нибудь сложная конструкция типа `ctx.chat.member.data.fields.meta.id`)

В данном случае `ctx.chat.id` уже довольно простая конструкция и можно использовать её напрямую, не вынося в константу. (далее по коду то же самое)

2024-03-14 10:35 UTC, Kreozot commented on app.js
> +        }
Обрати внимание на выравнивание.

Можешь поставить себе плагин ESLint в VS code. Он будет проверять форматирование кода и автоматически исправлять какие-то ошибки.

2024-03-14 18:21 UTC, soboleva8 commented on app.js
> +const textMessage = data.comment_rules;
В прошлый раз у меня, почему-то, строка выдавалась не отформатированной, когда просто приходила их .env
И Chat GPT рекомендовал такое решение. Я посмотрел на него и из пояснений GPT понял, что в .env хранится всё в формате текста HTML операторы воспринимаются как текст.
Тогда мне это показалось логичным.
Что надо разобрать строку, а потом собрать с учётом правил.
Но сейчас исправил и код получает комментарий из .env в строковом формате и через parse_mode:  'HTML' форматируется нужным образом.
Почему в прошлый раз пошло не так - не понятно.

2024-03-14 18:50 UTC, soboleva8 commented on app.js
> +        }
ESLint установил.
Выравнивание поправил.

2024-03-14 18:52 UTC, soboleva8 commented on app.js
> +        const commentChatId = ctx.chat.id;
Понял. Поправил.

2024-03-14 18:52 UTC, soboleva8 commented on app.js
>  const CHANNEL_ID = +process.env.CHANNEL_ID;
Добавил библиотеку.
Переписал код согласно документации.

2024-03-14 18:53 UTC, soboleva8 commented on app.js
> +    console.dir(ctx.message, { depth: null });
Все вызовы console.log удалил.

2024-03-20 17:53 UTC, soboleva8 commented
Переработанная версия кода, очищенная от лишних элементов.
Использован запрос к API через Bot.on и Bot.start()
Все ключевые переменные отправлены в .env
Использована библиотека envalid для системного преобразования типа переменных из .env

2024-03-20 17:53 UTC, merged